### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by syf097** [bdew-minecraft/pressure#27]
when i installed bdlib1.5.0 Advanced Generators 0.9.3 and Pressure Pipes 0.9.5,it crashed.
then i renewed Pressure Pipes 0.9.5 to Pressure Pipes 1.0.0,it worked.what's wrong?

---- Minecraft Crash Report ----
// There are four lights!

Time: 14-11-2 下午9:52
Description: Initializing game

java.lang.RuntimeException: Config parsing failed at 1.1: string matching regex `\z' expected but`c' found
    at scala.sys.package$.error(package.scala:27)
    at net.bdew.lib.recipes.RecipeParser.doParse(RecipeParser.scala:161)
    at net.bdew.lib.recipes.RecipeLoader.load(RecipeLoader.scala:418)
    at net.bdew.pressure.config.TuningLoader$.load(Tuning.scala:48)
    at net.bdew.pressure.Pressure$.preInit(Pressure.scala:49)
    at net.bdew.pressure.Pressure.preInit(Pressure.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at scala.sys.package$.error(package.scala:27)
    at net.bdew.lib.recipes.RecipeParser.doParse(RecipeParser.scala:161)
    at net.bdew.lib.recipes.RecipeLoader.load(RecipeLoader.scala:418)
    at net.bdew.pressure.config.TuningLoader$.load(Tuning.scala:48)
    at net.bdew.pressure.Pressure$.preInit(Pressure.scala:49)
    at net.bdew.pressure.Pressure.preInit(Pressure.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:134)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (x86) version 6.1
    Java Version: 1.7.0_67, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 312933640 bytes (298 MB) / 651984896 bytes (621 MB) up to 1037959168 bytes (989 MB)
    JVM Flags: 1 total; -Xmx1024M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.25.1208 Minecraft Forge 10.13.0.1208 59 mods loaded, 59 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{7.10.25.1208} [Forge Mod Loader](forge-1.7.10-10.13.0.1208.jar) Unloaded->Constructed->Pre-initialized
    Forge{10.13.0.1208} [Minecraft Forge](forge-1.7.10-10.13.0.1208.jar) Unloaded->Constructed->Pre-initialized
    appliedenergistics2-core{rv1-beta-12} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    CodeChickenCore{1.0.3.23} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    NotEnoughItems{1.0.3.51} [Not Enough Items]([NEI]NotEnoughItems-1.7.10-1.0.3.51-universal.jar) Unloaded->Constructed->Pre-initialized
    InputFix{1.7.x-v2} [InputFix](minecraft.jar) Unloaded->Constructed->Pre-initialized
    Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    OpenEye{0.6} [OpenEye](OpenEye-0.6-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    bspkrsCore{6.14} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.14.jar) Unloaded->Constructed->Pre-initialized
    Treecapitator{1.7.2} [Treecapitator]([1.7.2]Treecapitator-universal-2.0.3.jar) Unloaded->Constructed->Pre-initialized
    appliedenergistics2{rv1-beta-12} [Applied Energistics 2]([AE]appliedenergistics2-rv1-beta-12.jar) Unloaded->Constructed->Pre-initialized
    IC2{2.2.647-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.647-experimental.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Core{6.0.18} [BuildCraft](buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized
    Forestry{3.0.0.90} [Forestry for Minecraft]([F]forestry_1.7.10-3.0.0.90.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons{1.12.0.4} [NEI Addons]([NEI+]neiaddons-mc1710-1.12.0.4.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|ExtraBees{1.12.0.4} [NEI Addons: Extra Bees]([NEI+]neiaddons-mc1710-1.12.0.4.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|Forestry{1.12.0.4} [NEI Addons: Forestry]([NEI+]neiaddons-mc1710-1.12.0.4.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|CraftingTables{1.12.0.4} [NEI Addons: Crafting Tables]([NEI+]neiaddons-mc1710-1.12.0.4.jar) Unloaded->Constructed->Pre-initialized
    NEIAddons|ExNihilo{1.12.0.4} [NEI Addons: Ex Nihilo]([NEI+]neiaddons-mc1710-1.12.0.4.jar) Unloaded->Constructed->Pre-initialized
    NEIPlugins{1.1.0.7-unofficial} [NEI Plugins Unofficial]([NEI+]NEIPlugins-MC1.7.10-1.1.0.7-unofficial.jar) Unloaded->Constructed->Pre-initialized
    DamageIndicatorsMod{3.2.0} [Damage Indicators]([Sub]DamageIndicatorsMod-3.2.0.jar) Unloaded->Constructed->Pre-initialized
    inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks]([Sub]InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized
    MouseTweaks{2.4.4} [Mouse Tweaks]([Sub]MouseTweaks-2.4.4-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized
    zyinhud{1.3.4} [Zyin's HUD]([Sub]ZyinsHUD-%281.7.10%29-v.1.3.4.jar) Unloaded->Constructed->Pre-initialized
    AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels](AdvancedSolarPanel-1.7.10-3.5.1.jar) Unloaded->Constructed->Pre-initialized
    bdlib{1.5.0.31} [BD Lib](bdlib-mc1710-1.5.0.31.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Builders{6.0.18} [BC Builders](buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Energy{6.0.18} [BC Energy](buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Factory{6.0.18} [BC Factory](buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Transport{6.0.18} [BC Transport](buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Silicon{6.0.18} [BC Silicon](buildcraft-6.0.18.jar) Unloaded->Constructed->Pre-initialized
    ComputerCraft{1.64pr4} [ComputerCraft](ComputerCraft1.64pr4.jar) Unloaded->Constructed->Pre-initialized
    eplus{1.7.10-3.0.0a2} [Enchanting Plus](EnchantingPlus-1.7.10-3.0.0a2.jar) Unloaded->Constructed->Pre-initialized
    EnderIO{1.7.10-2.0.0.191} [Ender IO](EnderIO-1.7.10-2.0.0.191.jar) Unloaded->Constructed->Pre-initialized
    EnderStorage{1.4.5.22} [EnderStorage](EnderStorage-1.7.10-1.4.5.22-universal.jar) Unloaded->Constructed->Pre-initialized
    GalacticraftCore{3.0.1} [Galacticraft Core](GalacticraftCore-BETA-1.7-3.0.1.176.jar) Unloaded->Constructed->Pre-initialized
    GalacticraftMars{3.0.1} [Galacticraft Planets](Galacticraft-Planets-BETA-1.7-3.0.1.176.jar) Unloaded->Constructed->Pre-initialized
    advgenerators{0.9.3.22} [Advanced Generators](generators-mc1710-0.9.3.22.jar) Unloaded->Constructed->Pre-initialized
    IC2NuclearControl{1.7.10.01} [Nuclear Control](ic2nc-1.7.10-1.7.10.01.jar) Unloaded->Constructed->Pre-initialized
    ImmibisCore{59.0.3} [Immibis Core](immibis-core-59.0.3.jar) Unloaded->Constructed->Pre-initialized
    IronChest{6.0.49.733} [Iron Chest](ironchest-1.7.10-6.0.49.733-universal.jar) Unloaded->Constructed->Pre-initialized
    LogisticsPipes{0.8.0.58} [Logistics Pipes](logisticspipes-0.8.0.58.jar) Unloaded->Constructed->Pre-initialized
    NBTEdit{1.7.2.2} [In-game NBTEdit](NBTEdit_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    Railcraft{9.3.1.0} [Railcraft](Railcraft_1.7.10-9.3.1.0.jar) Unloaded->Constructed->Pre-initialized
    PowerConverters{1.7.10-3.0.0.25} [Power Converters](PowerConverters-1.7.10-3.0.0.25.jar) Unloaded->Constructed->Pre-initialized
    ForgeMultipart{1.1.0.307} [Forge Multipart](ForgeMultipart-1.7.10-1.1.0.307-universal.jar) Unloaded->Constructed->Pre-initialized
    pressure{0.9.5.33} [Pressure Pipes](pressure-mc1710-0.9.5.33.jar) Unloaded->Constructed->Errored
    ProjRed|Core{4.5.0.50} [ProjectRed](ProjectRed-Base-1.7.10-4.5.0.50.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Integration{4.5.0.50} [ProjectRed-Integration](ProjectRed-Integration-1.7.10-4.5.0.50.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Transmission{4.5.0.50} [ProjectRed-Transmission](ProjectRed-Integration-1.7.10-4.5.0.50.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Illumination{4.5.0.50} [ProjectRed-Illumination](ProjectRed-Lighting-1.7.10-4.5.0.50.jar) Unloaded->Constructed->Pre-initialized
    YogpstopLib{2.0-RC4} [Yogpstop Library](QuarryPlus-1.7.10-2.0-RC4.jar) Unloaded->Constructed->Pre-initialized
    QuarryPlus{2.0-RC4} [QuarryPlus](QuarryPlus-1.7.10-2.0-RC4.jar) Unloaded->Constructed->Pre-initialized
    ReiMinimap{1.7.10} [Rei's Minimap](ReiMinimap-1.7.10-3.6_CN by wolski.jar) Unloaded->Constructed->Pre-initialized
    Waila{1.5.3} [Waila](Waila-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    WailaNBT{1.4} [Waila NBT](WailaNBT-1.7.10-1.4.jar) Unloaded->Constructed->Pre-initialized
    McMultipart{1.1.0.307} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.0.307-universal.jar) Unloaded->Constructed->Pre-initialized
    ForgeMicroblock{1.1.0.307} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.0.307-universal.jar) Unloaded->Constructed->Pre-initialized
    AE2 Version: beta rv1-beta-12 for Forge 10.13.0.1187
    Launched Version: tech
    LWJGL: 2.9.1
    OpenGL: AMD Radeon HD 6350A Graphics GL version 3.2.9752 Compatibility Profile Context, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: [BDcraft Musics Pack.zip, Sphax PureBDcraft  64x MC1.7.4.zip, BDcraft Sounds Pack (1).zip]
Current Language: 简体中文 (中国)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by bdew** [comment]
BdLib 1.5.0 is too new for Pressure Pipes 0.9.5, it should work with 1.0
