### ISSUE TITLE
here is a server crash

### ISSUE THREAD

**Issue by Flukethoughts** [bdew-minecraft/pressure#32]
java.lang.NoSuchMethodError: net.minecraft.world.IBlockAccess.func_72800_K()I
    at net.bdew.pressure.misc.Helper$$anonfun$getPipeConnections$4.apply(Helper.scala:114)
    at net.bdew.pressure.misc.Helper$$anonfun$getPipeConnections$4.apply(Helper.scala:113)
    at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:259)
    at scala.collection.immutable.List.foreach(List.scala:383)
    at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:258)
    at scala.collection.TraversableLike$class.filter(TraversableLike.scala:270)
    at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
    at net.bdew.pressure.misc.Helper$.getPipeConnections(Helper.scala:113)
    at net.bdew.pressure.blocks.BlockPipe$.func_149719_a(BlockPipe.scala:40)
    at net.minecraft.block.Block.func_149731_a(Block.java:713)
    at net.minecraft.world.World.func_147447_a(World.java:1597)
    at net.minecraft.world.World.func_72901_a(World.java:1405)
    at net.minecraft.network.NetHandlerPlayServer.func_147350_a(NetHandlerPlayServer.java:1400)
    at net.minecraft.network.play.client.C0APacketAnimation.func_148833_a(SourceFile:43)
    at net.minecraft.network.play.client.C0APacketAnimation.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
    at java.lang.Thread.run(Thread.java:745)

**Comment by Flukethoughts** [comment]
thank you that was fast
