### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by winsrp** [bdew-minecraft/pressure#61]
I'll just leave this here... no idea what went on.

```
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  BetterFoliageLoader (BetterFoliage-MC1.8.x-2.0.3.jar)
  MMMCoremod (LittleMaidMobNX-NX5B40-1.8.x.jar)
  FMLPlugin (InventoryTweaks-1.60-beta-38.jar)
  MovingWorldCoreMod (movingworld-MC1.8.9-INDEV-E-full.jar)
  NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
Contact their authors BEFORE contacting forge

// Everything's going to plan. No, really, that was supposed to happen.

Time: 2/27/16 10:48 PM
Description: Ticking block entity

java.lang.AbstractMethodError: net.bdew.pressure.blocks.tank.blocks.TilePressureOutput.getWorld()Lnet/minecraft/world/World;
    at net.bdew.pressure.pressurenet.Helper$.recalculateConnectionInfo(Helper.scala:78)
    at net.bdew.pressure.blocks.tank.blocks.TilePressureOutput$$anonfun$doOutput$1.apply(PressureOutput.scala:50)
    at net.bdew.pressure.blocks.tank.blocks.TilePressureOutput$$anonfun$doOutput$1.apply(PressureOutput.scala:48)
    at scala.Option.foreach(Option.scala:245)
    at net.bdew.pressure.blocks.tank.blocks.TilePressureOutput.doOutput(PressureOutput.scala:48)
    at net.bdew.pressure.blocks.tank.blocks.TilePressureOutput.doOutput(PressureOutput.scala:31)
    at net.bdew.lib.multiblock.interact.CIOutputFaces$$anonfun$doOutputs$2$$anonfun$apply$1.apply(CIOutputFaces.scala:61)
    at net.bdew.lib.multiblock.interact.CIOutputFaces$$anonfun$doOutputs$2$$anonfun$apply$1.apply(CIOutputFaces.scala:57)
    at scala.Option.foreach(Option.scala:245)
    at net.bdew.lib.multiblock.interact.CIOutputFaces$$anonfun$doOutputs$2.apply(CIOutputFaces.scala:57)
    at net.bdew.lib.multiblock.interact.CIOutputFaces$$anonfun$doOutputs$2.apply(CIOutputFaces.scala:56)
    at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778)
    at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
    at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
    at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
    at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
    at scala.collection.mutable.HashMap.foreach(HashMap.scala:99)
    at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777)
    at net.bdew.lib.multiblock.interact.CIOutputFaces$class.doOutputs(CIOutputFaces.scala:56)
    at net.bdew.pressure.blocks.tank.controller.TileTankController.doOutputs(TileTankController.scala:33)
    at net.bdew.lib.multiblock.interact.CIOutputFaces$$anonfun$1.apply$mcV$sp(CIOutputFaces.scala:42)
    at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
    at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
    at scala.collection.immutable.List.foreach(List.scala:383)
    at net.bdew.lib.Event0.trigger(Event.scala:19)
    at net.bdew.lib.tile.TileTicking$class.update(TileTicking.scala:24)
    at net.bdew.lib.multiblock.tile.TileControllerGui.func_73660_a(TileControllerGui.scala:14)
    at net.minecraft.world.World.func_72939_s(World.java:1718)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:250)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at net.bdew.pressure.pressurenet.Helper$.recalculateConnectionInfo(Helper.scala:78)
    at net.bdew.pressure.blocks.tank.blocks.TilePressureOutput$$anonfun$doOutput$1.apply(PressureOutput.scala:50)
    at net.bdew.pressure.blocks.tank.blocks.TilePressureOutput$$anonfun$doOutput$1.apply(PressureOutput.scala:48)
    at scala.Option.foreach(Option.scala:245)
    at net.bdew.pressure.blocks.tank.blocks.TilePressureOutput.doOutput(PressureOutput.scala:48)
    at net.bdew.pressure.blocks.tank.blocks.TilePressureOutput.doOutput(PressureOutput.scala:31)
    at net.bdew.lib.multiblock.interact.CIOutputFaces$$anonfun$doOutputs$2$$anonfun$apply$1.apply(CIOutputFaces.scala:61)
    at net.bdew.lib.multiblock.interact.CIOutputFaces$$anonfun$doOutputs$2$$anonfun$apply$1.apply(CIOutputFaces.scala:57)
    at scala.Option.foreach(Option.scala:245)
    at net.bdew.lib.multiblock.interact.CIOutputFaces$$anonfun$doOutputs$2.apply(CIOutputFaces.scala:57)
    at net.bdew.lib.multiblock.interact.CIOutputFaces$$anonfun$doOutputs$2.apply(CIOutputFaces.scala:56)
    at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:778)
    at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
    at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:99)
    at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:230)
    at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
    at scala.collection.mutable.HashMap.foreach(HashMap.scala:99)
    at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777)
    at net.bdew.lib.multiblock.interact.CIOutputFaces$class.doOutputs(CIOutputFaces.scala:56)
    at net.bdew.pressure.blocks.tank.controller.TileTankController.doOutputs(TileTankController.scala:33)
    at net.bdew.lib.multiblock.interact.CIOutputFaces$$anonfun$1.apply$mcV$sp(CIOutputFaces.scala:42)
    at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
    at net.bdew.lib.Event0$$anonfun$trigger$1.apply(Event.scala:19)
    at scala.collection.immutable.List.foreach(List.scala:383)
    at net.bdew.lib.Event0.trigger(Event.scala:19)
    at net.bdew.lib.tile.TileTicking$class.update(TileTicking.scala:24)
    at net.bdew.lib.multiblock.tile.TileControllerGui.func_73660_a(TileControllerGui.scala:14)

-- Block entity being ticked --
Details:
    Name: pressure.TankController // net.bdew.pressure.blocks.tank.controller.TileTankController
    Block type: ID #727 (tile.pressure.TankController // net.bdew.pressure.blocks.tank.controller.BlockTankController$)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-474,5,-513), Chunk: (at 6,0,15 in -30,-33; contains blocks -480,0,-528 to -465,255,-513), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
    Actual block type: ID #727 (tile.pressure.TankController // net.bdew.pressure.blocks.tank.controller.BlockTankController$)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1718)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)

-- Affected level --
Details:
    Level name: Test World
    All players: 0 total; []
    Chunk stats: ServerChunkCache: 625 Drop: 0
    Level seed: 600846917139021824
    Level generator: ID 01 - flat, ver 0. Features enabled: true
    Level generator options: 
    Level spawn location: -474.00,4.00,-585.00 - World: (-474,4,-585), Chunk: (at 6,0,7 in -30,-37; contains blocks -480,0,-592 to -465,255,-577), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
    Level time: 266972 game time, 6000 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 1145 (now: false), thunder time: 125802 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:250)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
    at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
    Minecraft Version: 1.8.9
    Operating System: Windows 10 (amd64) version 10.0
    CPU: 8x Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1141323792 bytes (1088 MB) / 2341150720 bytes (2232 MB) up to 4281597952 bytes (4083 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.19 Powered by Forge 11.15.1.1762 Optifine OptiFine_1.8.9_HD_U_H4_pre 43 mods loaded, 43 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1762.jar) 
    UCHIJAAAA   Forge{11.15.1.1762} [Minecraft Forge] (forge-1.8.9-11.15.1.1762.jar) 
    UCHIJAAAA   OldModelLoader{5.0.40} [LMMNX OldModelLoader] (minecraft.jar) 
    UCHIJAAAA   darkevilmac.movingworld.common.asm.coremod{} [MovingWorld CORE] (minecraft.jar) 
    UCHIJAAAA   MovingWorld{MC1.8.9-INDEV-E} [Moving World] (movingworld-MC1.8.9-INDEV-E-full.jar) 
    UCHIJAAAA   ArchimedesShipsPlus{MC1.8.9-INDEV-D} [Archimedes' Ships Plus] (archimedesshipsplus-MC1.8.9-INDEV-D.jar) 
    UCHIJAAAA   ArchitectureCraft{1.3.1} [ArchitectureCraft] (ArchitectureCraft-1.3.1-mc1.8.9.jar) 
    UCHIJAAAA   bdlib{1.10.0.23} [BD Lib] (bdlib-1.10.0.23-mc1.8.9.jar) 
    UCHIJAAAA   BetterAchievements{0.1.1} [Better Achievements] (BetterAchievements-1.8.9-0.1.1.jar) 
    UCHIJAAAA   BetterFoliage{2.0.3} [Better Foliage] (BetterFoliage-MC1.8.x-2.0.3.jar) 
    UCHIJAAAA   BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8.9-3.0.0.1839-universal.jar) 
    UCHIJAAAA   bookshelfapi{2.3.4} [Bookshelf] (Bookshelf-API-1.8.9-2.3.4.jar) 
    UCHIJAAAA   cfmce{1.0} [MrCrayfish's Furniture Mod: Community Edition] (cfmce-1.0-mc1.8.9.jar) 
    UCHIJAAAA   net.blacklab.lib{3.3.13} [EBLib] (EBLib-EL3B13-1.8.x.jar) 
    UCHIJAAAA   EnderZoo{1.8.9-1.1.3.35} [Ender Zoo] (EnderZoo-1.8.9-1.1.3.35.jar) 
    UCHIJAAAA   substratum{1.1.0.1} [Substratum] (Substratum-1.8.9-1.1.0.1.jar) 
    UCHIJAAAA   foundry{1.4.0.0} [Foundry] (Foundry-1.8.9-1.4.0.0.jar) 
    UCHIJAAAA   pressure{1.3.0.16} [Pressure Pipes] (pressure-1.3.0.16-mc1.8.9.jar) 
    UCHIJAAAA   advgenerators{0.9.19.3} [Advanced Generators] (generators-0.9.19.3-mc1.8.9.jar) 
    UCHIJAAAA   IGWMod{1.2.4-4} [In-Game wiki Mod] (IGW-Mod-1.8.9-1.2.4-4-universal.jar) 
    UCHIJAAAA   inventorytweaks{1.60-beta-38-b8950ce} [Inventory Tweaks] (InventoryTweaks-1.60-beta-38.jar) 
    UCHIJAAAA   IronChest{6.0.125.770} [Iron Chest] (ironchest-1.8.9-6.0.125.770.jar) 
    UCHIJAAAA   JEI{2.28.5.172} [Just Enough Items] (jei_1.8.9-2.28.5.172.jar) 
    UCHIJAAAA   journeymap{5.1.3} [JourneyMap] (journeymap-1.8.8-5.1.3-unlimited.jar) 
    UCHIJAAAA   lmmnxapi{13} [LMMNX API] (LittleMaidMobNX-NX5B40-1.8.x.jar) 
    UCHIJAAAA   lmmx{5.0.40} [LittleMaidMobNX] (LittleMaidMobNX-NX5B40-1.8.x.jar) 
    UCHIJAAAA   MMMLibX{5.0.40} [MMMLibX] (LittleMaidMobNX-NX5B40-1.8.x.jar) 
    UCHIJAAAA   RadixCore{1.8.9-2.1.0} [RadixCore] (RadixCore-1.8.9-2.1.0-universal.jar) 
    UCHIJAAAA   MCA{1.8.9-5.1.1.2} [Minecraft Comes Alive] (MCA-1.8.9-5.1.1.2-universal.jar) 
    UCHIJAAAA   MoreFurnaces{1.5.0} [More Furnaces] (MoreFurnaces-1.5.0-MC1.8.9.jar) 
    UCHIJAAAA   cfm{3.6} [MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.6.1(1.8.9).jar) 
    UCHIJAAAA   fodc{1.7.2} [Ore Dictionary Converter] (OreDictionaryConverter-1.7.2.jar) 
    UCHIJAAAA   PneumaticCraft{1.13.7-11} [PneumaticCraft] (PneumaticCraft-1.8.9-1.13.7-11-universal.jar) 
    UCHIJAAAA   progressiveautomation{1.6.35} [Progressive Automation] (ProgressiveAutomation-1.8.9-1.6.35.jar) 
    UCHIJAAAA   redstonepaste{1.7.2} [Redstone Paste] (redstonepaste-mc1.8.8-1.7.2.jar) 
    UCHIJAAAA   Roguelike{1.4.5} [Roguelike Dungeons] (RoguelikeDungeons-1.8.9-1.4.5.jar) 
    UCHIJAAAA   wuppy29_simplerecipes{1.9.0} [Simple Recipes] (Simple Recipes 1.8.0-1.9.0.jar) 
    UCHIJAAAA   storagenetwork{1.7.3} [Storage Network] (StorageNetwork-1.8.9-1.7.3.jar) 
    UCHIJAAAA   usefulrecipes{1.1} [UsefulRecipes] (UsefulRecipes-1.1.0(1.8.9).jar) 
    UCHIJAAAA   usefulstones{0.2} [Useful Stones] (UsefulStones_0.2-MCv1.8.9.jar) 
    UCHIJAAAA   Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
    UCHIJAAAA   wawla{1.4.7} [What Are We Looking At] (Wawla-1.4.7-1.8+.jar) 
    Loaded coremods (and transformers): 
BetterFoliageLoader (BetterFoliage-MC1.8.x-2.0.3.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
MMMCoremod (LittleMaidMobNX-NX5B40-1.8.x.jar)
  mmmlibx.lib.multiModel.MMMLoader.MMMTransformer
FMLPlugin (InventoryTweaks-1.60-beta-38.jar)
  invtweaks.forge.asm.ContainerTransformer
MovingWorldCoreMod (movingworld-MC1.8.9-INDEV-E-full.jar)

NowWithRendering (redstonepaste-mc1.8.8-1.7.2.jar)
  net.fybertech.nwr.NowWithRendering
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    List of loaded APIs: 
        * BetterAchievements|API (0.1.1) from BetterAchievements-1.8.9-0.1.1.jar
        * CoFHAPI (1.8.9R1.2.0B1) from Foundry-1.8.9-1.4.0.0.jar
        * CoFHAPI|block (1.8.9R1.2.0B1) from ProgressiveAutomation-1.8.9-1.6.35.jar
        * CoFHAPI|energy (1.8.9R1.2.0B1) from StorageNetwork-1.8.9-1.7.3.jar
        * CoFHAPI|tileentity (1.8.9R1.2.0B1) from ProgressiveAutomation-1.8.9-1.6.35.jar
        * foundry.api (1.4.0.0) from Foundry-1.8.9-1.4.0.0.jar
        * JustEnoughItemsAPI (3.1.0) from jei_1.8.9-2.28.5.172.jar
        * LMMNX API (5.0.40) from LittleMaidMobNX-NX5B40-1.8.x.jar
        * PneumaticCraftApi (1.0) from PneumaticCraft-1.8.9-1.13.7-11-universal.jar
        * pressureAPI (1.3.0.16) from pressure-1.3.0.16-mc1.8.9.jar
        * WailaAPI (1.3) from Waila-1.6.0-B3_1.8.8.jar
    Profiler Position: N/A (disabled)
    Player Count: 0 / 8; []
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    OptiFine Version: OptiFine_1.8.9_HD_U_H4_pre
    Render Distance Chunks: 16
    Mipmaps: 4
    Anisotropic Filtering: 1
    Antialiasing: 0
    Multitexture: false
    Shaders: KUDA-Shaders v6.1.13 BETA - Ultra.zip
    OpenGlVersion: 4.5.0 NVIDIA 358.91
    OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
    OpenGlVendor: NVIDIA Corporation
    CpuCount: 8`
```

**Comment by bdew** [comment]
Bleh, looks like md-5/SpecialSource#31 strikes back. Will fix ASAP.

**Comment by bdew** [comment]
Should be fixed in this build: http://minecraft.curseforge.com/projects/pressure-pipes/files/2284354
If you have Advanced Generators you'll need to update it as well (http://minecraft.curseforge.com/projects/advanced-generators/files/2284358)
