### ISSUE TITLE
crash on server 1.7.10

### ISSUE THREAD

**Issue by changemenemo** [bdew-minecraft/pressure#90]
```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 12/7/16 11:32 AM
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: codechicken/multipart/MultiPartRegistry$IPartFactory2
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.NoClassDefFoundError: codechicken/multipart/MultiPartRegistry$IPartFactory2
	at net.bdew.pressure.Pressure$.preInit(Pressure.scala:61)
	at net.bdew.pressure.Pressure.preInit(Pressure.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 5 more
Caused by: java.lang.ClassNotFoundException: codechicken.multipart.MultiPartRegistry$IPartFactory2
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 33 more
Caused by: java.lang.NullPointerException


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 4.4.0-53-generic
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 567262784 bytes (540 MB) / 1004011520 bytes (957 MB) up to 4225236992 bytes (4029 MB)
	JVM Flags: 8 total; -Xmx4096M -Xms1024M -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:MaxGCPauseMillis=40 -XX:CMSInitiatingOccupancyFraction=70 -XX:+CMSScavengeBeforeRemark -XX:+AggressiveOpts
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 45 mods loaded, 45 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCH	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCH	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCH	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCH	MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) 
	UCH	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCH	OpenComputers|Core{1.6.0.9} [OpenComputers (Core)] (minecraft.jar) 
	UCH	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCH	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCH	bdlib{1.9.4.109} [BD Lib] (bdlib-1.9.4.109-mc1.7.10.jar) 
	UCH	CoFHCore{1.7.10R3.1.3} [CoFH Core] (CoFHCore-[1.7.10]3.1.3-327.jar) 
	UCH	ThermalFoundation{1.7.10R1.2.5} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.5-115.jar) 
	UCH	ThermalExpansion{1.7.10R4.1.4} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.4-247.jar) 
	UCH	BigReactors{0.4.5B} [Big Reactors] (BigReactors-0.4.5B.jar) 
	UCH	BuildCraft|Core{7.1.18} [BuildCraft] (buildcraft-7.1.18.jar) 
	UCH	BuildCraft|Transport{7.1.18} [BC Transport] (buildcraft-7.1.18.jar) 
	UCH	BuildCraft|Silicon{7.1.18} [BC Silicon] (buildcraft-7.1.18.jar) 
	UCH	BuildCraft|Energy{7.1.18} [BC Energy] (buildcraft-7.1.18.jar) 
	UCH	BuildCraft|Factory{7.1.18} [BC Factory] (buildcraft-7.1.18.jar) 
	UCH	BuildCraft|Builders{7.1.18} [BC Builders] (buildcraft-7.1.18.jar) 
	UCH	BuildCraft|Robotics{7.1.18} [BC Robotics] (buildcraft-7.1.18.jar) 
	UCH	IC2{2.2.825-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.825-experimental.jar) 
	UCH	Forestry{4.2.16.64} [Forestry for Minecraft] (forestry_1.7.10-4.2.16.64.jar) 
	UCH	BuildCraft|Compat{7.1.5} [BuildCraft Compat] (buildcraft-compat-7.1.5.jar) 
	UCH	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	UCH	CompactSolars{4.4.41.316} [Compact Solar Arrays] (CompactSolars-1.7.10-4.4.41.316-universal.jar) 
	UCH	ComputerCraft{1.75} [ComputerCraft] (ComputerCraft1.75.jar) 
	UCH	EnderStorage{1.4.7.38} [EnderStorage] (EnderStorage-1.7.10-1.4.7.38-universal.jar) 
	UCH	ForgeEssentials{1.4.4} [Forge Essentials] (forgeessentials-1.7.10-1.4.4.1187-server.jar) 
	UCH	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCH	ForgeMultipart{1.1.0.309} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) 
	UCH	OpenComputers{1.6.0.9} [OpenComputers] (OpenComputers-MC1.7.10-1.6.0.9-universal.jar) 
	UCH	MapWriter{2.1.2} [MapWriter] (Opis-1.2.5_1.7.10.jar) 
	UCH	Opis{1.2.5} [Opis] (Opis-1.2.5_1.7.10.jar) 
	UCE	pressure{1.3.0.131} [Pressure Pipes] (pressure-1.3.0.131-mc1.7.10.jar) 
	UCH	Railcraft{9.12.2.0} [Railcraft] (Railcraft_1.7.10-9.12.2.0.jar) 
	UCH	ThermalDynamics{1.7.10R1.2.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.2.0-171.jar) 
	UCH	Translocator{1.1.2.16} [Translocator] (Translocator-1.7.10-1.1.2.16-universal.jar) 
	UCH	worldedit{6.1.1-SNAPSHOT} [WorldEdit] (worldedit-forge-mc1.7.10-6.1.1-SNAPSHOT-dist.jar) 
	UCH	WR-CBE|Core{1.4.1.11} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.11-universal.jar) 
	UCH	WR-CBE|Addons{1.4.1.11} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.11-universal.jar) 
	UCH	WR-CBE|Logic{1.4.1.11} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.11-universal.jar) 
	UCH	McMultipart{1.1.0.309} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) 
	UCH	ForgeMicroblock{1.1.0.309} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) 
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.1.3-327
	ThermalFoundation: -[1.7.10]1.2.5-115
	ThermalExpansion: -[1.7.10]4.1.4-247
	ForgeEssentials: Running ForgeEssentials 1.4.4.1187 (7d9640c). Modules loaded: Afterlife, Backups, Chat, Commands, Economy, Multiworld, Permissions, PlayerLogger, Protection, Remote, Scripting, SignTools, Teleport, Tickets, WEIntegrationTools, WorldBorder, factions, mapper
	ThermalDynamics: -[1.7.10]1.2.0-171
	List of loaded APIs: 
		* appliedenergistics2|API (rv2) from appliedenergistics2-rv2-stable-10.jar
		* Baubles|API (1.0.1.10) from ThermalFoundation-[1.7.10]1.2.5-115.jar
		* BuildCraftAPI|blocks (1.0) from buildcraft-7.1.18.jar
		* BuildCraftAPI|blueprints (1.5) from buildcraft-7.1.18.jar
		* BuildCraftAPI|boards (2.0) from buildcraft-7.1.18.jar
		* BuildCraftAPI|core (1.0) from buildcraft-7.1.18.jar
		* BuildCraftAPI|crops (1.1) from Railcraft_1.7.10-9.12.2.0.jar
		* BuildCraftAPI|events (2.0) from buildcraft-7.1.18.jar
		* BuildCraftAPI|facades (1.1) from buildcraft-7.1.18.jar
		* BuildCraftAPI|filler (4.0) from buildcraft-7.1.18.jar
		* BuildCraftAPI|fuels (2.0) from buildcraft-7.1.18.jar
		* BuildCraftAPI|gates (4.1) from buildcraft-7.1.18.jar
		* BuildCraftAPI|items (1.1) from Railcraft_1.7.10-9.12.2.0.jar
		* BuildCraftAPI|library (2.0) from Railcraft_1.7.10-9.12.2.0.jar
		* BuildCraftAPI|lists (1.0) from buildcraft-7.1.18.jar
		* BuildCraftAPI|power (1.3) from buildcraft-7.1.18.jar
		* BuildCraftAPI|recipes (3.0) from buildcraft-7.1.18.jar
		* BuildCraftAPI|robotics (3.0) from buildcraft-7.1.18.jar
		* BuildCraftAPI|statements (1.1) from buildcraft-7.1.18.jar
		* BuildCraftAPI|tablet (1.0) from buildcraft-7.1.18.jar
		* BuildCraftAPI|tiles (1.2) from Railcraft_1.7.10-9.12.2.0.jar
		* BuildCraftAPI|tools (1.0) from buildcraft-7.1.18.jar
		* BuildCraftAPI|transport (4.1) from buildcraft-7.1.18.jar
		* CoFHAPI (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHAPI|block (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHAPI|core (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHAPI|energy (1.7.10R1.0.2) from Railcraft_1.7.10-9.12.2.0.jar
		* CoFHAPI|fluid (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHAPI|inventory (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHAPI|item (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHAPI|modhelpers (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHAPI|tileentity (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHAPI|transport (1.7.10R1.0.1) from buildcraft-compat-7.1.5.jar
		* CoFHAPI|world (1.7.10R1.3.1) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|audio (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|gui (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|gui|container (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|gui|element (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|gui|element|listbox (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|gui|slot (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|inventory (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|render (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|render|particle (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|util (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|util|helpers (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|util|position (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|world (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* CoFHLib|world|feature (1.7.10R1.1.2) from CoFHCore-[1.7.10]3.1.3-327.jar
		* ComputerCraft|API (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|FileSystem (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Lua (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Media (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Peripheral (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Permissions (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Redstone (1.75) from ComputerCraft1.75.jar
		* ComputerCraft|API|Turtle (1.75) from ComputerCraft1.75.jar
		* ForestryAPI|apiculture (4.8.0) from forestry_1.7.10-4.2.16.64.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.7.10-4.2.16.64.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.7.10-4.2.16.64.jar
		* ForestryAPI|core (5.0.0) from forestry_1.7.10-4.2.16.64.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.7.10-4.2.16.64.jar
		* ForestryAPI|food (1.1.0) from forestry_1.7.10-4.2.16.64.jar
		* ForestryAPI|fuels (2.0.1) from forestry_1.7.10-4.2.16.64.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.7.10-4.2.16.64.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.7.10-4.2.16.64.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.7.10-4.2.16.64.jar
		* ForestryAPI|mail (3.0.0) from forestry_1.7.10-4.2.16.64.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.7.10-4.2.16.64.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.7.10-4.2.16.64.jar
		* ForestryAPI|storage (3.0.0) from forestry_1.7.10-4.2.16.64.jar
		* ForestryAPI|world (2.1.0) from forestry_1.7.10-4.2.16.64.jar
		* Forge-FEHooks (1448.2) from forgeessentials-1.7.10-1.4.4.1187-server.jar
		* ForgeEssentialsAPI (2.0) from forgeessentials-1.7.10-1.4.4.1187-server.jar
		* ForgeEssentialsAPI|Economy (2.0) from forgeessentials-1.7.10-1.4.4.1187-server.jar
		* ForgeEssentialsAPI|Perms (2.0) from forgeessentials-1.7.10-1.4.4.1187-server.jar
		* ForgeEssentialsAPI|Remote (2.0) from forgeessentials-1.7.10-1.4.4.1187-server.jar
		* IC2API (1.0) from industrialcraft-2-2.2.825-experimental.jar
		* OpenComputersAPI|Component (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.9-universal.jar
		* OpenComputersAPI|Core (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.9-universal.jar
		* OpenComputersAPI|Driver (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.9-universal.jar
		* OpenComputersAPI|Driver|Item (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.9-universal.jar
		* OpenComputersAPI|Event (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.9-universal.jar
		* OpenComputersAPI|FileSystem (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.9-universal.jar
		* OpenComputersAPI|Internal (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.9-universal.jar
		* OpenComputersAPI|Machine (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.9-universal.jar
		* OpenComputersAPI|Manual (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.9-universal.jar
		* OpenComputersAPI|Network (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.9-universal.jar
		* OpenComputersAPI|Prefab (6.0.0-alpha) from OpenComputers-MC1.7.10-1.6.0.9-universal.jar
		* pressureAPI (1.3.0.131) from pressure-1.3.0.131-mc1.7.10.jar
		* RailcraftAPI|bore (1.0.0) from Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|carts (1.6.0) from Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|core (1.5.0) from Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|crafting (1.0.0) from Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|electricity (2.0.0) from Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|events (1.0.0) from Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|fuel (1.0.0) from Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|helpers (1.1.0) from Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|items (1.0.0) from Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|locomotive (1.1.0) from Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|signals (2.3.0) from Railcraft_1.7.10-9.12.2.0.jar
		* RailcraftAPI|tracks (2.3.0) from Railcraft_1.7.10-9.12.2.0.jar
		* Thaumcraft|API (4.2.2.0) from Railcraft_1.7.10-9.12.2.0.jar
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by changemenemo** [comment]
I've tried with 130 also

**Comment by bdew** [comment]
> 	UCH	ForgeMultipart{1.1.0.309} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.309-universal.jar) 

Your FMP version is too old. http://files.minecraftforge.net/ForgeMultipart/

**Comment by changemenemo** [comment]
indeed but seems a problem from forgeessentials or forge because I didn't download this mod so it was a dependencies of one of them
